settings:
  check-players-at-game-start: false
  min-players: 2
  max-players: 24
  physics-enabled: false
  gamerules:
    pvp: true

lobby:
  world: mm__lobby
  spawn-pos: 5 27 13
  spawn-yaw: 225
  npcs:
    join:
      pos: 8 28 10
      text1: '&l&cQuickPlay'
      text2: '&dJoin: &a%s%d &e%d&7/&e%d'
      default-yaw: 45
      skin-file: global/skins/minigame-lobby-join.png
    back-to-hub:
      pos: -8 28 10
      text1: '&l&6Back To Hub'
      text2: '&d%d &eplaying'
      default-yaw: -45
      skin-file: global/skins/minigame-lobby-back-to-hub.png
  holograms:
    main:
      pos: 0 29 9

game:
  duration: 420
  ending-duration: 10
  ui-update-ticks: 10
  murderer-damage-multiplier: 2.5
  time-start-tracking: 60
  items:
    sword:
      name: '&o&l&cMurderstick'
      throw-cooldown: 7
      throw-speed: 3
    blaze-rod:
      name: '&o&l&6Lights Out'
      blindness-duration: 20
    hoe:
      name: '&o&l&9Sheriff Hoe'
      shoot-cooldown: 0.2
      friendly-fire-death: true
      raycast-max-distance: 100
      raycast-step: 0.2
    yellow-dye:
      name: '&o&l&eCraft The Gun &r&7( Hold / Right Click )'
  gold:
    spawn-interval-min: 2
    spawn-interval-max: 3
  exp:
    per-gold: 10
    per-kill: 15
    murderer-kills-sheriff: 100
    sheriff-kills-murderer: 600
  coins:
    per-kill: 25
    murderer-kills-sheriff: 300
    sheriff-kills-murderer: 800
  dead-body:
    head-yaw-offset: -35
    head-pitch-offset: -40

waiting-lobby:
  world: mm__waitinglobby
  spawn-pos: 2431 32 2430
  spawn-yaw: 0
  npcs:
    leave:
      pos: 2433 32 2436
      text1: '&l&eReturn To Lobby'
      default-yaw: 0
      skin-file: global/skins/waiting-lobby-return-to-lobby.png
  items:
    rules-book:
      name: '&o&l&fRules &r&7- Hold / Right Click'
      title: Murder Mystery Rules
      author: '@Woona, @BlueWillow'
      content:
      - |-
        &lHow to play &aMurder&2Mystery&r&l!

        &r&8Rules...
        - No Hacking (Creative, Fly Hacks, Etc.)
        - No inappropriate language or Content
        - No Impersonating other players since We can't see your actual name during game. (EXAMPLE: "I'm Kylie, I suck")...
      - |-
        &lHow to play:

        &r&8here are 3 types of players randomly chosen each round, one &cMurderer&r&8, one &9Sheriff&r&8, and the rest of the players are
        &aCivilians/Innocents&r&8.
      - |-
        &l&cMurderer&r&8: 
        &r&8The Murderer's Objective is to kill every single player in the game with out getting killed by the &9Sheriff&r&8. Be on the look out for a player (&9Sheriff&r&8) with a golden hoe because that player can kill you.
      - |-
        &l&9Sheriff/Detective&r&8: 
        &r&8The Sheriff's Objective is to Kill the &cMurderer&r&8 using the Sheriff's gun (Golden Hoe) by pressing and holding the screen to shoot at the &cMurderer&r&8. Note: If you Shoot at an Innocent and he/she isn't the Murderer, you're automatically eliminated.
      - |-
        &l&aCivilians/Innocent&r&8: 
        &r&8The Innocent's/Civilians Objective is to survive, collect 5 Gold ingots to buy the Sheriff's Gun (Golden Hoe) to become the new &9Sheriff&r&8 when the game needs a new one. Another objective is not to get killed until the &cMurderer&r&8 either gets killed or runs out of time.
      - |-
        &lHow To Craft Sheriffs gun?&r&8

        1.) Gather ATLEAST 5 gold ingots.
        2.) Wait till &9Sheriff/Detective&r&8 dies or leaves.
        3.) Hold and Click Yellow Dye By having it in your hand.
      - |-
        &lRoles and their Weapons!

        &l&cMurderer&r&8: Iron Sword/Knife (one hit one kill) and can throw their sword (Hold and Click)
        &l&9Sheriff&r&8: Golden Hoe/Sheriff's Gun (Hold and Click)
        &l&aInnocents&r&8: N/A (civilians and innocents work together)