settings:
  check-players-at-game-start: false
  min-players: 2
  max-players: 24
  physics-enabled: false
  gamerules:
    pvp: true

lobby:
  world: mm__lobby
  spawn-pos: 5 27 13
  spawn-yaw: 225
  npc:
    join:
      pos: 8 28 10
      text1: '&l&cQuickPlay'
      text2: '&dJoin: &a%s%d &e%d&7/&e%d'
      default-yaw: 45
      skin-file: global/skins/minigame-lobby-join.png
    back-to-hub:
      pos: -8 28 10
      text1: '&l&6Back To Hub'
      text2: '&d%d &eplaying'
      default-yaw: -45
      skin-file: global/skins/minigame-lobby-back-to-hub.png

game:
  duration: 420
  ending-duration: 10
  ui-update-ticks: 10
  murderer-damage-multiplier: 2.5
  time-start-tracking: 60
  items:
    sword:
      name: '&o&l&cMurderstick'
      throw-cooldown: 10
      throw-speed: 30
    blaze-rod:
      name: '&o&l&6Lights Out'
      blindness-duration: 20
    hoe:
      name: '&o&l&9Sheriff Hoe'
      shoot-cooldown: 0.2
      friendly-fire-death: true
      raycast-max-distance: 100
      raycast-step: 0.2
    yellow-dye:
      name: '&o&l&eCraft The Gun &r&7( Hold / Right Click )'
  gold:
    spawn-interval-min: 2
    spawn-interval-max: 3
  exp:
    per-gold: 10
    per-kill: 15
    murderer-kills-sheriff: 100
    sheriff-kills-murderer: 600
  coins:
    per-kill: 25
    murderer-kills-sheriff: 300
    sheriff-kills-murderer: 800
  dead-body:
    head-yaw-offset: -35
    head-pitch-offset: -40

waiting-lobby:
  world: mm__waitinglobby
  spawn-pos: 2431 32 2430
  spawn-yaw: 0
  npc:
    leave:
      pos: 2433 32 2436
      text1: '&l&eReturn To Lobby'
      default-yaw: 0
      skin-file: global/skins/waiting-lobby-return-to-lobby.png
  items:
    rules-book:
      name: '&o&l&fRules &r&7- Hold / Right Click'
      title: Murder Mystery Rules
      author: '@Woona, @BlueWillow'
      content:
      - |-
        &lHow to play &aMurder&2Mystery&r&l!

        &r&8Rules...
        - No Hacking (Creative, Fly Hacks, Etc.)
        - No inappropriate language or Content
        - No Impersonating other players since We can't see your actual name during game. (EXAMPLE: "I'm Kylie, I suck")...
      - |-
        &lHow to play:

        &r&8here are 3 types of players randomly chosen each round, one &cMurderer&r&8, one &9Sheriff&r&8, and the rest of the players are
        &aCivilians/Innocents&r&8.
      - |-
        &l&cMurderer&r&8: 
        &r&8The Murderer's Objective is to kill every single player in the game with out getting killed by the &9Sheriff&r&8. Be on the look out for a player (&9Sheriff&r&8) with a golden hoe because that player can kill you.
      - |-
        &l&9Sheriff/Detective&r&8: 
        &r&8The Sheriff's Objective is to Kill the &cMurderer&r&8 using the Sheriff's gun (Golden Hoe) by pressing and holding the screen to shoot at the &cMurderer&r&8. Note: If you Shoot at an Innocent and he/she isn't the Murderer, you're automatically eliminated.
      - |-
        &l&aCivilians/Innocent&r&8: 
        &r&8The Innocent's/Civilians Objective is to survive, collect 5 Gold ingots to buy the Sheriff's Gun (Golden Hoe) to become the new &9Sheriff&r&8 when the game needs a new one. Another objective is not to get killed until the &cMurderer&r&8 either gets killed or runs out of time.
      - |-
        &lHow To Craft Sheriffs gun?&r&8

        1.) Gather ATLEAST 5 gold ingots.
        2.) Wait till &9Sheriff/Detective&r&8 dies or leaves.
        3.) Hold and Click Yellow Dye By having it in your hand.
      - |-
        &lRoles and their Weapons!

        &l&cMurderer&r&8: Iron Sword/Knife (one hit one kill) and can throw their sword (Hold and Click)
        &l&9Sheriff&r&8: Golden Hoe/Sheriff's Gun (Hold and Click)
        &l&aInnocents&r&8: N/A (civilians and innocents work together)

map-settings:
  default-map: thegrandhotel
  enabled-maps:
  - museum
  - school_n
  - thegrandhotel
  - fnaf6
  - abandonedschool
  maps:
    test:
      name: Test
      world: world
      min: 0 80 0
      max: 100 80 100
      night-vision: false
      weather: clear
      builders:
      - ItzDS35
      builders-team: '@BrokenLens Community'
      spawns:
      - 50 80 50
      - 20 80 20
      - 80 80 80
    museum:
      name: Museum
      world: mm_map_museum
      min: -63 0 -95
      max: 81 45 58
      night-vision: true
      weather: clear
      builders:
      - Lesz
      builders-team: '@BrokenLens BuildTeam'
      spawns:
      - 12 5 0
      - 30 5 -23
      - -31 5 -13
      - 16 5 -56
      - 53 5 33
      - 65 5 -6
      - 14 5 -86
      - -41 5 -61
      - 1 24 4
      - 11 8 -26
      - 1 13 -26
      - 71 6 -44
    village:
      name: Minetown
      world: mm_map_village
      min: -11 -2 -72
      max: 133 60 145
      night-vision: true
      weather: clear
      builders:
      - Yoursenpaiisme
      - Amphinous
      builders-team: '@Community'
      spawns:
      - 13 4 5
      - 63 6 20
      - 55 4 -6
      - 50 5 -61
      - 75 4 10
      - 86 4 15
      - 58 6 -24
      - 66 4 -4
      - 44 6 -4
      - 71 10 36
      - 58 10 78
      - 86 5 99
      - 55 7 56
      - 45 14 86
      - 22 4 -5
    school_n:
      name: School N
      world: mm_map_school_n
      min: 2427 31 2406
      max: 2468 64 2469
      night-vision: false
      weather: clear
      builders:
      - TrenzKGM
      - KhrizKGM
      builders-team: '@BrokenLens BuildTeam'
      spawns:
      - 2446 56 2438
      - 2436 52 2441
      - 2446 48 2431
      - 2435 48 2425
      - 2438 48 2454
      - 2444 40 2442
      - 2446 40 2429
      - 2435 40 2421
      - 2460 40 2426
      - 2456 32 2455
      - 2436 33 2459
      - 2445 32 2453
      - 2438 32 2441
      - 2446 48 2435
      - 2436 44 2441
      - 2435 32 2433
      - 2456 33 2428
      - 2447 32 2411
    thegrandhotel:
      name: The Grand Hotel
      world: mm_map_thegrandhotel
      min: 2434 30 2357
      max: 2515 73 2432
      night-vision: true
      weather: clear
      builders:
      - TrenzKGM
      builders-team: '@BrokenLens BuildTeam'
      spawns:
      - 2457 32 2419
      - 2486 34 2411
      - 2467 32 2405
      - 2464 33 2378
      - 2483 33 2373
      - 2501 33 2373
      - 2506 42 2387
      - 2490 42 2383
      - 2484 50 2369
      - 2482 50 2382
      - 2499 50 2382
      - 2485 46 2361
      - 2484 34 2364
      - 2504 58 2376
      - 2481 66 2367
      - 2494 67 2382
      - 2470 67 2387
      - 2484 32 2418
      - 2505 33 2410
      - 2444 32 2384
    fnaf6:
      name: FNAF 6
      world: mm_map_fnaf6
      min: 2383 20 2390
      max: 2451 45 2461
      night-vision: true
      weather: clear
      builders:
      - TrenzKGM
      - KhrizKGM
      builders-team: '@BrokenLens BuildTeam'
      spawns:
      - 2409 25 2446
      - 2390 27 2450
      - 2406 27 2456
      - 2416 25 2457
      - 2415 25 2446
      - 2430 28 2439
      - 2442 25 2443
      - 2445 26 2436
      - 2447 23 2424
      - 2445 26 2412
      - 2441 25 2405
      - 2429 25 2407
      - 2422 25 2438
      - 2422 25 2428
      - 2422 25 2417
      - 2417 25 2404
      - 2405 25 2404
      - 2396 25 2408
      - 2403 25 2415
      - 2409 25 2411
      - 2409 25 2422
      - 2401 25 2425
      - 2396 25 2431
      - 2404 25 2435
      - 2416 32 2423
      - 2426 28 2425
      - 2429 28 2428
      - 2428 28 2423
      - 2431 28 2426
      - 2387 25 2401
      - 2388 27 2411
      - 2387 27 2423
      - 2389 27 2436
      - 2416 29 2410
    abandonedschool:
      name: Abandoned School
      world: mm_map_abandonedschool
      min: -23 3 -24
      max: 58 28 28
      night-vision: false
      weather: rain
      builders:
      - TrenzKGM
      - KhrizKGM
      builders-team: '@BrokenLens BuildTeam'
      spawns:
      - 13 21 16
      - 27 21 9
      - 1 21 18
      - -7 14 9
      - -8 14 0
      - 0 14 8
      - 8 14 8
      - -1 14 -8
      - 9 14 19
      - 16 14 6
      - 26 14 -1
      - 38 14 8
      - 26 14 21
      - 52 14 7
      - 49 14 -5
      - 41 14 19
      - 50 14 22
      - -8 10 -11
      - -1 5 -9
      - 8 5 -2
      - 16 5 7
      - 8 5 18
      - -7 5 17
      - 25 10 7
      - 26 5 15
      - 35 5 10
      - 28 5 -2
      - 41 5 -1
      - 25 5 -16
      - 44 5 -15