name: brlnsreb
main: org.brlnsreb.BrlnsReb
version: "${version}"
api: "3.0.0"
author: brlnsreb
description: BrokenLens Reborn plugin
  
permissions:
  admin:
    description: Admin commands
    default: op