name: brlnsreb minigames
main: com.brlnsreb.minigames.MinigameCore
version: "1.1.0"
api: "2.0.0"
author: brlnsreb
description: BrokenLens Reborn Minigames plugin
  
permissions:
  mm.admin:
    description: Admin commands
    default: op