world: generallobby
spawn-pos: 
npc:
  list:
  - mm
  mm:
    pos: 0 0 0
    text1: '&atest1'
    text2: test2 %d
    default-yaw: 0
    skin-file: skins/test.png

items:
  games: 
    name: '&l&o&6BrokenLens Games&r &7Hold / Right click'
    title: 'BrokenLens Games'
    hub-button-text: 'BrokenLens HUB'
  menu: 
    name: '&l&o&eBroken&6Lens &dMenu&r &7Hold / Right click'
  magic-staff: 
    name: '&l&o&dMagic Staff&r &7Hold / Right click'
  join-game: 
    name: '&l&o&eJoin Game&r &7Hold / Right click'