server-under-maintenance: false

lobby:
  items:
    games: 
      name: '&l&o&6BrokenLens Games&r &7Hold / Right click'
      title: 'BrokenLens Games'
      hub-button-text: 'BrokenLens HUB'
    menu: 
      name: '&l&o&eBroken&6Lens &dMenu&r &7Hold / Right click'
    magic-staff: 
      name: '&l&o&dMagic Staff&r &7Hold / Right click'
    join-game: 
      name: '&l&o&eJoin Game&r &7Hold / Right click'

match:
  waiting-lobby:
    countdown-seconds: 45
    shortened-countdown-seconds: 10
    bossbar:
      medium-threshold-seconds: 60
      short-threshold-seconds: 10
      text-long: '&l&eStarting in &6%dm %ds'
      text-medium: '&l&eStarting in &6%ds'
      text-short: '&l&eStarting in &c%ds'
      text-waiting-players: '&l&cWaiting For Players'
    items:
      game-poll:
        name: '&o&l&dGame Poll &r&7- Hold / Right Click'
        times:
        - Day
        - Sunrise
        - Sunset
        - Night

  game:
    pregame-countdown-seconds: 10
    items:
      spectator:
        teleporter:
          name: '&l&o&eTeleporter'
        actions:
          name: '&l&o&eActions'

  death-lobby:
    world: _deathlobby
    spawn-pos: 71 10 -146
    spawn-yaw: -90
    npc:
      play-again:
        pos: 74 11 -148
        text1: '&l&aPlay Again'
        default-yaw: 90
        skin-file: global/skins/death-lobby-play-again.png
      spectate:
        pos: 75 11 -146
        text1: '&l&9Spectate'
        default-yaw: 90
        skin-file: global/skins/death-lobby-spectate.png
      return-to-lobby:
        pos: 74 11 -144
        text1: '&l&cReturn To Lobby'
        default-yaw: 0
        skin-file: global/skins/death-lobby-return-to-lobby.png
