world: _mainhub
spawn-pos: 2431 39 2431
spawn-yaw: 90
npc:
  list:
  - mm
  mm:
    pos: 2387 38 2431
    text1: '&l&aMurder&2Mystery'
    text2: '&d%d &eplaying'
    default-yaw: -90
    skin-file: main_hub/skins/mm.png